language: php

php:
    - 5.3
    - 5.4

before_script:
    - composer install
    - cp phpunit.xml.dist phpunit.xml

script: phpunit

notifications:
    email:
        - benjamin.lazarecki@gmail.com
